### ISSUE TITLE
Table switch -c has no effect, file content is just displayed as usal (e.g. by calling "ov -c -d: /etc/passwd"). Using ov Version 0.4.0. Same effect with $HEAD. Distro is Mint 19.3.

### ISSUE THREAD

**Issue by noborus** [noborus/ov#21]
Table switch -c has no effect, file content is just displayed as usal (e.g. by calling "ov -c -d: /etc/passwd"). Using ov Version 0.4.0. Same effect with $HEAD. Distro is Mint 19.3.

_Originally posted by @larsklemstein in https://github.com/noborus/ov/issues/5#issuecomment-671629179_

**Comment by noborus** [comment]
I don't know yet.
It worked with me.

https://github.com/noborus/ov/blob/master/docs/image.md#column-mode-toggle-c
Does the highlight do not work on the left or right?

**Comment by larsklemstein** [comment]
The highlighting works on the left.

Lars

Am Di., 11. Aug. 2020 um 06:46 Uhr schrieb Noboru Saito <
notifications@github.com>:

**Comment by noborus** [comment]
ls -l won't work because the delimiter will be multiple spaces. 
#251 implementation is required to resolve.
For now, the only thing you can do is:
```
ls -l |tr -s ' ' '\t'|ov -d '\t' --column-mode --column-rainbow
```

**Comment by ilius** [comment]
I don't think that PR will resolve this.
Tabular data is not just about a delimiter.
The padding/alignment of columns (left, right or center) should be taken into account.
Because there may be columns (like dates, file names, etc) that have spaces.

Parsing tabular data accurately and correctly is not even always possible, since they may be ambiguity. But it's still worth to try our best, because there are so many Linux/Unix command line tools that produce it (and are not able to produce csv or json, sadly).

The README actually clams:

> `ov` also has an effective function for tabular text.

which made me think it can actually parse tabular data.

**Comment by ilius** [comment]
A simple example of how tabular data can be ambiguis:

```
ov $ ls -l '--time-style=+%Y-%m-%d %H:%M:%S'
total 140
-rw-rw-r-- 1 s s  1110 2023-01-17 03:04:55 config_test.go
drwxrwxr-x 2 s s  4096 2023-01-17 03:04:55 docs
drwxrwxr-x 6 s s  4096 2023-01-17 03:04:55 examples
-rw-rw-r-- 1 s s  1766 2023-01-17 03:04:55 go.mod
-rw-rw-r-- 1 s s 54608 2023-01-17 03:04:55 go.sum
-rw-rw-r-- 1 s s  1069 2023-01-17 03:04:55 LICENSE
-rw-rw-r-- 1 s s 12842 2023-01-17 03:04:55 main.go
-rw-rw-r-- 1 s s   545 2023-01-17 03:04:55 Makefile
-rw-rw-r-- 1 s s   207 2023-01-17 03:04:55 ov-disable-default.yaml
drwxrwxr-x 2 s s  4096 2023-01-17 03:04:55 oviewer
-rw-rw-r-- 1 s s  3901 2023-01-17 03:04:55 ov-less.yaml
-rw-rw-r-- 1 s s  3658 2023-01-17 03:04:55 ov.yaml
-rw-rw-r-- 1 s s 22001 2023-01-17 03:04:55 README.md
drwxrwxr-x 2 s s  4096 2023-01-17 03:04:55 testdata
```

Are date and time in the same column or two different columns?
It may not matter much here, but in some other unlucky cases, it can be important.

**Comment by noborus** [comment]
> The README actually claims:
> 
> > `ov` also has an effective function for tabular text.
> 
> which made me think it can actually parse tabular data.

I think it is unreasonable.
The output of `ls -l` is actually vertically aligned rather than tabular. So the README is not wrong.

Anyway, vertical alignment is difficult to parse.

**Comment by ilius** [comment]
I think in the context of command line (and not spreadsheets), vertical alignment is part of tabular output/data, because command line output is generally meant for viewing, searching or filtering (with grep/sed), not parsing.

Formats like csv and tsv are also tabular, but they are mostly spreadsheet-oriented I think.

Ideally all commands that print tables should be able to produce csv, tsv or json by giving a flag, but that's very far-fetching.

**Comment by noborus** [comment]
My reply remains unchanged, just repeating, but converted to discussions.
