### ISSUE TITLE
wrong column width

### ISSUE THREAD

**Issue by nkh** [noborus/ov#422]
using command: ps aux|ov -H1 --column-width --column-rainbow

![screenshot_2023-08-04_14-55-45](https://github.com/noborus/ov/assets/45409/d74f9686-aaf5-4e99-8eb4-13501f20916a)

scrolling right 

![screenshot_2023-08-04_14-56-41](https://github.com/noborus/ov/assets/45409/ec5ff6be-ff69-4b6f-87e3-dfecc1d4d52f)

**Comment by noborus** [comment]
Thank you for raising the issue.
I need more explanation. I don't know what's wrong with some of the images.

**Comment by nkh** [comment]
first image: first column, you can see that 'systemd+' doesn't have the same width as the other rows

second image: selecting next column (6 times), you can see parts of  a column that should be hidden (4 and 8 in blue)

**Comment by noborus** [comment]
thank you for your reply.
Ultimately, this is by design.
column-width supports overhanging columns.
Therefore, it is interpreted that the point pointed out is protruding.
![Screenshot from 2023-08-05 11-32-09](https://github.com/noborus/ov/assets/2296563/fd1123bf-d162-4eb5-b544-61c1cdb24b6a)

You might think that USER(systemd+) and pid are not overrun.
The conclusion is that left- and right-aligned boundaries are hard to guess and subject to interpretation.

**Comment by nkh** [comment]
this is very basic case and the guess is obviously bad looking at your own screenshot

--column-delimiter does a good job
