### ISSUE TITLE
Escape sequences

### ISSUE THREAD

**Issue by ccoVeille** [noborus/ov#660]
What about using this lib?

https://github.com/charmbracelet/sequin

**Comment by noborus** [comment]
hank you.
I tried it, but I think it is still insufficient.

The `ov` has already reproduced the behavior of an incorrect escape sequence.
This is to reduce the display of the display due to the `ov`.

![Screenshot from 2024-11-20 07-11-01](https://github.com/user-attachments/assets/db65b56a-1ec0-413d-9f3f-101bd3939f9f)

If a '-' is specified where a number should be specified, the specification is ignored and `Hello` is displayed.

If '@' is specified here, it means the end of the escape sequence and `;4mHello` is displayed.

The `ov` implementation already achieves these.

**Comment by ccoVeille** [comment]
Is there a need for sequin to handle more things?

**Comment by noborus** [comment]
I felt their policy was a little different from ov's.
